### PR TITLE
Fix: Remix dev asset server web socket error

### PR DESCRIPTION
**Pull request by tkovis**
Further description about the bug in https://github.com/remix-run/remix/issues/2958. I had this very issue today and the workaround was to add devServerPort: 8002 here.

### CODE REVIEW

**Comment by mcansh** [comment]
thanks for the report, as you noted, this is an upstream issue that we're fixing in Remix :)

**Comment by machour** [comment]
@mcansh The upstream issue have been fixed, is this change still needed?

**Comment by mcansh** [comment]
> @mcansh The upstream issue have been fixed, is this change still needed?

livereload itself still isn't great for "unbundled" servers (importing "./build"), but we did fix the default devServerPort, so technically yes this is fixed

**Comment by kentcdodds** [comment]
Thanks anyway @tkovis!

**Pull request closed without merging**
