### PR TITLE
chore: add npmrc with legacy-peer-deps

### PR DESCRIPTION
**Pull request by mcansh**

### CODE REVIEW

**Review by kentcdodds — APPROVED** [review]
Looks good 👍

**Comment by Xiphe** [comment]
why is this required?

**Comment by mcansh** [comment]
> why is this required?

we're using React 18 and a surprising number of libraries don't have React 18 as a peer dep yet, instead they're mostly `"react": "^16.8.0 || ^17.0.0"` which makes npm (v7+) throw an error when installing, npm 6 behaved differently by not installing peer dependencies automatically - more info can be found here https://stackoverflow.com/a/66620869

**Comment by Xiphe** [comment]
ok, I understand.

**Pull request merged**
