### PR TITLE
Update vite in package.json

### PR DESCRIPTION
**Pull request by cypherpower**

### CODE REVIEW

**Comment by cypherpower** [comment]
Fix for issue #180

**Review by McNouvion — APPROVED** [review]
Just ran into this issue on a fresh install :) Thanks.

**Comment by quantuminformation** [comment]
so are we using vite for all the remix build in this stack now?

**Comment by scottmuangsrichan** [comment]
Are they going to merge this pull request. Cloned this repo to test out and got the same error as stated in this pull request. Easy fix to go and update the version number just wondering if they are going to merge this request so that further developers don't face this issue again.

**Pull request closed without merging**
