### PR TITLE
feat: enable `v2_dev` flag

### PR DESCRIPTION
**Pull request by MichaelDeBoey**

### CODE REVIEW

**Review by pcattori — APPROVED** [review]
@MichaelDeBoey can you run this locally and try editing markup,styles,loaders to make sure HMR and HDR are working?

**Comment by MichaelDeBoey** [comment]
@pcattori I keep getting the following error:

```sh
sandbox failed! Plugin error:
- Local env var conflicts with plugin:
- 'testing' variable 'NODE_ENV'
Error: Plugin error:
- Local env var conflicts with plugin:
- 'testing' variable 'NODE_ENV'
```

Maybe @lpsinger can point me into the right direction to fix this error as well 🤔

**Comment by lpsinger** [comment]
> @pcattori I keep getting the following error:
> 
> ```shell
> sandbox failed! Plugin error:
> - Local env var conflicts with plugin:
> - 'testing' variable 'NODE_ENV'
> Error: Plugin error:
> - Local env var conflicts with plugin:
> - 'testing' variable 'NODE_ENV'
> ```
> 
> Maybe @lpsinger can point me into the right direction to fix this error as well 🤔

Do you have a `.env` or a `preferences.arc` file that defines `NODE_ENV`? If so, remove it.

**Comment by MichaelDeBoey** [comment]
@lpsinger it was indeed in the `.env` file

The Arc template is talking about needing to create a a `preferences.arc` file in the root with the following contents:

```
@sandbox
livereload false
# NODE_ENV development is required when running the dev server
@env
testing
  NODE_ENV development
```
I guess this is not true then? 🤔

**Comment by MichaelDeBoey** [comment]
@pcattori The app is running, but it seems like I'm still missing something as HMR isn't working yet

**Comment by lpsinger** [comment]
> @lpsinger it was indeed in the `.env` file
> 
> The Arc template is talking about needing to create a a `preferences.arc` file in the root with the following contents:
> 
> ```
> @sandbox
> livereload false
> 
> # NODE_ENV development is required when running the dev server
> @env
> testing
>   NODE_ENV development
> ```
> 
> I guess this is not true then? 🤔

Oops! I didn't see those. My recent PRs made those instructions unnecessary. See https://github.com/remix-run/remix/pull/6796.

**Pull request closed without merging**
