### PR TITLE
chore: update dependencies

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
Major versions now

### CODE REVIEW

**Comment by MichaelDeBoey** [comment]
I think the Cypress problem is a caching problem or so, as these tests are passing locally 😕

**Review by kentcdodds — APPROVED** [review]
Thanks!

**Comment by kentcdodds** [comment]
Maybe the GitHub action needs to be updated?

**Comment by MichaelDeBoey** [comment]
It seems like it does 👍
https://github.com/cypress-io/github-action/releases/tag/v4.0.0

Fixed in #68

**Pull request merged**
